export const AttributeTagHierarchyObj = {
  Size: {
    tags: [
      'S',
      'M',
      'L',
      'XL',
      'XXL',
      '3XL',
      '75ml',
      '100ml',
      '150ml',
      '200ml',
      '250ml',
      '500ml',
      '28',
      '30',
      '32',
      '34',
      '36',
      '38',
    ],
    isDefault: true,
  },
  Color: {
    tags: [
      'Black',
      'Red',
      'Blue',
      'Green',
      'White',
      'Yellow',
      'Purple',
      'Pink',
      'Grey',
      'Navy',
      'Olive',
      'Maroon',
      'Orange',
      'Brown',
    ],
    isDefault: true,
  },

  Sleeves: {
    tags: ['Short ', 'Long ', 'Sleeveless'],
    isDefault: false,
  },

  Material: {
    tags: [
      'Cotton',
      'Wool',
      'Silk',
      'Polyester',
      'Linen',
      'Leather',
      'Denim',
      'Iron',
      'Gold',
      'Aluminum',
      'Silver',
      'Titanium',
      'Plastic',
    ],
    isDefault: false,
  },

  Neckline: {
    tags: [
      'RoundNeck',
      'VNeck',
      'Collared',
      'Turtleneck',
      'BoatNeck',
      'ScoopNeck',
      'Halter',
    ],
    isDefault: false,
  },

  Fit: {
    tags: ['Slim', 'Regular', 'Loose', 'Athletic'],
    isDefault: false,
  },

  Pattern: {
    tags: [
      'Solid',
      'Striped',
      'Checked',
      'Printed',
      'Floral',
      'PolkaDot',
      'Paisley',
    ],
    isDefault: false,
  },
  Occasion: {
    tags: [
      'Casual Wear',
      'Formal Wear',
      'Business Wear  ',
      'Party Wear',
      'Wedding Wear',
      'Beach Wear',
      'Holiday Wear',
      'Office Wear',
      'Club Wear',
      'Weekend Wear',
      'Everyday Wear',
    ],
    isDefault: false,
  },
};
