export enum SettingEnum {
  SHIPPING_FEE = 'SHIPPING_FEE',
  BASE_CURRENCY = 'BASE_CURRENCY',
  REFUND_POLICY = 'REFUND_POLICY',
  SHIPPING_POLICY = 'SHIPPING_POLICY',
  PRIVACY_POLICY = 'PRIVACY_POLICY',
  TERMS_OF_SERVICE = 'TERMS_OF_SERVICE',
  CONTACT_INFORMATION = 'CONTACT_INFOMATION',
}
