version: '3.8'
services:
  postgres:
    image: postgres:latest
    ports:
      - '5433:5432' # Changed host port to avoid conflicts
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: address_shop
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    ports:
      - '6380:6379' # Changed host port to avoid conflicts
    volumes:
      - redis-data:/data

  app:
    build: .
    ports:
      - '4008:4008'
    environment:
      NODE_ENV: development
      APP_PORT: 4008
      APP_NAME: "NestJS API"
      API_PREFIX: api
      APP_FALLBACK_LANGUAGE: en
      APP_HEADER_LANGUAGE: x-custom-lang
      FRONTEND_DOMAIN: http://192.168.1.42:3000
      BACKEND_DOMAIN: http://localhost:4008
      DATABASE_TYPE: postgres
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: 1234
      DATABASE_NAME: address_shop
      DATABASE_SYNCHRONIZE: 'true' # Note the quotes for boolean value
      DATABASE_MAX_CONNECTIONS: 100
      DATABASE_SSL_ENABLED: 'false' # Note the quotes for boolean value
      DATABASE_REJECT_UNAUTHORIZED: 'false' # Note the quotes for boolean value
      FILE_DRIVER: local
      # WORKER_HOST: redis://redis:6379/1
      REDIS_HOST: redis
      ADMIN_DEFAULT_DEVICE_ID: ADMIN_DEFAULT_DEVICE_ID
      MAIL_HOST: maildev
      MAIL_PORT: 1025
      MAIL_IGNORE_TLS: 'true' # Note the quotes for boolean value
      MAIL_SECURE: 'false' # Note the quotes for boolean value
      MAIL_REQUIRE_TLS: 'false' # Note the quotes for boolean value
      MAIL_DEFAULT_EMAIL: noreply@example.com
      MAIL_DEFAULT_NAME: Api
      MAIL_CLIENT_PORT: 1080
      AUTH_JWT_SECRET: secret
      AUTH_JWT_TOKEN_EXPIRES_IN: 15m
      AUTH_REFRESH_SECRET: secret_for_refresh
      AUTH_REFRESH_TOKEN_EXPIRES_IN: 3650d
      AUTH_FORGOT_SECRET: secret_for_forgot
      AUTH_FORGOT_TOKEN_EXPIRES_IN: 30m
      AUTH_CONFIRM_EMAIL_SECRET: secret_for_confirm_email
      AUTH_CONFIRM_EMAIL_TOKEN_EXPIRES_IN: 1d
    depends_on:
      - postgres
      - redis

volumes:
  postgres-data:
  redis-data:
